import {
  AbsoluteFill,
  Audio,
  Sequence,
  staticFile,
} from "remotion";
import { OpenClawStory } from "./scenes/OpenClawStory";
import { HowItWorks } from "./scenes/HowItWorks";
import { FeatureHighlights } from "./scenes/FeatureHighlights";
import { LiveDemo } from "./scenes/LiveDemo";
import { CallToAction } from "./scenes/CallToAction";
import { RhythmOverlay } from "./effects/RhythmOverlay";
import { palette } from "./design";
import { narrationCues } from "./narrationCues";

/**
 * Fast-cut timeline (30fps, ~75s = 2250 frames)
 *
 * 22 beats across 5 acts:
 *   Act 1 — The AI Agent Story (6 beats, ~16s)
 *   Act 2 — How It Works (4 beats, ~11s)
 *   Act 3 — Feature Highlights (6 beats, ~17s)
 *   Act 4 — Live Demo (3 beats, ~9.5s)
 *   Act 5 — CTA (3 beats, ~8s)
 *
 * Scene layout is driven by `narrationCues.ts` (auto-generated by build_narration.sh).
 */
export const TtsIntro: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: palette.bg, overflow: "hidden" }}>
      {/* Narration audio track */}
      <Audio src={staticFile("ttscli_intro.wav")} />

      <AbsoluteFill>
        {/* Act 1 — The AI Agent Story */}
        <Sequence
          from={narrationCues.scenes.story.from}
          durationInFrames={narrationCues.scenes.story.duration}
        >
          <OpenClawStory />
        </Sequence>

        {/* Act 2 — How It Works */}
        <Sequence
          from={narrationCues.scenes.tech.from}
          durationInFrames={narrationCues.scenes.tech.duration}
        >
          <HowItWorks />
        </Sequence>

        {/* Act 3 — Feature Highlights */}
        <Sequence
          from={narrationCues.scenes.features.from}
          durationInFrames={narrationCues.scenes.features.duration}
        >
          <FeatureHighlights />
        </Sequence>

        {/* Act 4 — Live Demo */}
        <Sequence
          from={narrationCues.scenes.demo.from}
          durationInFrames={narrationCues.scenes.demo.duration}
        >
          <LiveDemo />
        </Sequence>

        {/* Act 5 — CTA */}
        <Sequence
          from={narrationCues.scenes.cta.from}
          durationInFrames={narrationCues.scenes.cta.duration}
        >
          <CallToAction />
        </Sequence>
      </AbsoluteFill>

      <RhythmOverlay
        totalFrames={narrationCues.totalFrames}
        cueFrames={[
          narrationCues.scenes.story.from,
          narrationCues.scenes.tech.from,
          narrationCues.scenes.features.from,
          narrationCues.scenes.demo.from,
          narrationCues.scenes.cta.from,
          narrationCues.totalFrames - 1,
        ]}
      />
    </AbsoluteFill>
  );
};
